### PR TITLE
Upgrade prince npm lib for security update.

### PR DESCRIPTION
**Pull request by bhatman**
Who else knows how to run/test this these days? :)

### CODE REVIEW

**Comment by huyhong** [comment]
We likely need to upgrade our Prince license as well, we purchased in 2015 and are only allowed 12 months of updates, and at the time we were on version 10. The Latest is version 12 (https://www.princexml.com/purchase/).

Also unsure if this negatively affects PDF rendering (lots of new CSS improvements have been added in the 2 version upgrades).

**Comment by huyhong** [comment]
@walterqian @tally38 Is there any chance ya'll could test the newer version of Prince since you're actively working on reports?

**Comment by tally38** [comment]
Had no idea how to do this until today; will do!

**Comment by huyhong** [comment]
Closing this as it's not properly tested and pulling a now-defunct version of prince

**Pull request closed without merging**
